/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import CSDL.tbBangDiem;
import CSDL.tbSinhVien;
import Models.clsBangDiem;
import Models.clsSinhVien;
import java.awt.Color;
import java.awt.Component;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tantanmanh
 */
public class frmBangDiemSV extends javax.swing.JFrame {
    String Msv = "";
    public frmQuanLySinhVien csQLSV;
    /**
     * Creates new form frmBangDiem
     */
    public frmBangDiemSV() {
        initComponents();
        tblBangDiem.getColumnModel().getColumn(0).setMaxWidth(65);
        tblBangDiem.getColumnModel().getColumn(1).setMaxWidth(65);
        tblBangDiem.getColumnModel().getColumn(2).setMaxWidth(250);
        tblBangDiem.getColumnModel().getColumn(3).setMaxWidth(100);
        tblBangDiem.getColumnModel().getColumn(4).setMaxWidth(120);
        changeTable(tblBangDiem,4);
    }
    public void HienthiDS(String Msv){
        tbBangDiem bangBangdiem = new tbBangDiem();
        tbSinhVien bangSinhvien = new tbSinhVien();
        clsSinhVien sv = bangSinhvien.LaySinhvien(Msv);
        System.out.print(sv.Msv);
        txtMsv.setText(this.Msv);
        txthoTen.setText(sv.hoTen);
        Vector<clsBangDiem> dsbangdiem = bangBangdiem.LayDSBangDiemSVSearch(Msv);
        if(dsbangdiem.size()>0)
        {
            DefaultTableModel dtm = (DefaultTableModel)tblBangDiem.getModel();
            dtm.setRowCount(0);//xóa các dòng cũ nếu có
            for(clsBangDiem bangdiem : dsbangdiem)
            {
             dtm.addRow(new Object[]{bangdiem.Msv,bangdiem.idMon,bangdiem.tenMon, bangdiem.diem, bangdiem.tinhTrang});
            }
        }
    }
    
    public void changeTable(JTable table, int column_index) {
        for(int i=0;i<=column_index;i++){
            table.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                    final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    String tinhtrang = table.getValueAt(row, 4).toString();
                    if (tinhtrang.equals("true")) {
                        c.setBackground(Color.GREEN);
                    } else {
                        c.setBackground(Color.RED);
                    }
                    return c;
                }
            });
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangDiem = new javax.swing.JTable();
        txtMsv = new javax.swing.JTextField();
        txthoTen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 300));
        setSize(new java.awt.Dimension(600, 300));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Msv", "ID", "Môn", "Điểm", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBangDiem.setPreferredSize(new java.awt.Dimension(375, 80));
        jScrollPane1.setViewportView(tblBangDiem);

        txthoTen.setEditable(false);
        txthoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoTenActionPerformed(evt);
            }
        });

        jLabel1.setText("MSV");

        jLabel2.setText("Họ Tên");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa điểm");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMsv, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txthoTen))
                .addGap(27, 27, 27)
                .addComponent(btnSearch)
                .addGap(36, 36, 36)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoTenActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String Msv = this.Msv;
        tbBangDiem bangBangdiem = new tbBangDiem();
        tbSinhVien bangSinhvien = new tbSinhVien();
        clsSinhVien sv = bangSinhvien.LaySinhvien(Msv);
        System.out.print(sv.Msv);
        txtMsv.setText(this.Msv);
        txthoTen.setText(sv.hoTen);
        Vector<clsBangDiem> dsbangdiem = bangBangdiem.LayDSBangDiemSVSearch(Msv);
        if(dsbangdiem.size()>0)
        {
            DefaultTableModel dtm = (DefaultTableModel)tblBangDiem.getModel();
            dtm.setRowCount(0);//xóa các dòng cũ nếu có
            for(clsBangDiem bangdiem : dsbangdiem)
            {
             dtm.addRow(new Object[]{bangdiem.Msv,bangdiem.idMon,bangdiem.tenMon, bangdiem.diem, bangdiem.tinhTrang});
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String Msv = txtMsv.getText();
        tbBangDiem bangBangdiem = new tbBangDiem();
        tbSinhVien bangSinhvien = new tbSinhVien();
        clsSinhVien sv = bangSinhvien.LaySinhvien(Msv);
        txthoTen.setText(sv.hoTen);
        Vector<clsBangDiem> dsbangdiem = bangBangdiem.LayDSBangDiemSV(Msv);
        if(dsbangdiem.size()>0)
        {
            DefaultTableModel dtm = (DefaultTableModel)tblBangDiem.getModel();
            dtm.setRowCount(0);//xóa các dòng cũ nếu có
            for(clsBangDiem bangdiem : dsbangdiem)
            {
             dtm.addRow(new Object[]{bangdiem.Msv,bangdiem.idMon,bangdiem.tenMon, bangdiem.diem, bangdiem.tinhTrang});
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        csQLSV.HienthiDSSinhvien();
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        clsBangDiem ttBangDiem = new clsBangDiem();
        int i = tblBangDiem.getSelectedRow();
         if(i<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn sinh viên");
        else
        {
            ttBangDiem.Msv = (String)tblBangDiem.getModel().getValueAt(i,0);
            ttBangDiem.idMon = (String)tblBangDiem.getModel().getValueAt(i,1);
            ttBangDiem.diem = (Float)tblBangDiem.getModel().getValueAt(i,3);
            ttBangDiem.tinhTrang = (Boolean)tblBangDiem.getModel().getValueAt(i,4);
            frmSuaDiem formSuaDiem = new frmSuaDiem();
            formSuaDiem.ttBangDiem = ttBangDiem;
            formSuaDiem.csBDSV = this;
            formSuaDiem.method =1;
            formSuaDiem.setVisible(true);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBangDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBangDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBangDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBangDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBangDiemSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBangDiem;
    private javax.swing.JTextField txtMsv;
    private javax.swing.JTextField txthoTen;
    // End of variables declaration//GEN-END:variables
}
