/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import CSDL.tbBangDiem;
import CSDL.tbLop;
import Models.clsBangDiem;
import Models.clsLop;
import java.awt.Color;
import java.awt.Component;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tantanmanh
 */
public class frmBangDiemL extends javax.swing.JFrame {
    String idLop = "";
    public frmQuanlyLop csQLLop;
    /**
     * Creates new form frmBangDiemL
     */
    public frmBangDiemL() {
        initComponents();
        tblBangDiem.getColumnModel().getColumn(0).setMaxWidth(65);
        tblBangDiem.getColumnModel().getColumn(1).setMaxWidth(150);
        tblBangDiem.getColumnModel().getColumn(2).setMaxWidth(65);
        tblBangDiem.getColumnModel().getColumn(3).setMaxWidth(65);
        tblBangDiem.getColumnModel().getColumn(4).setMaxWidth(250);
        tblBangDiem.getColumnModel().getColumn(5).setMaxWidth(50);
        changeTable(tblBangDiem,5);
    }
    public void HienthiDS(String idLop)
    {
        tbBangDiem bangBangdiem = new tbBangDiem();
        tbLop bangLop = new tbLop();
        clsLop lop = bangLop.LayLop(idLop);
        txtGVCN.setText(lop.GVCN);
        txtidLop.setText(this.idLop);
        Vector<clsBangDiem> dsbangdiem = bangBangdiem.LayDSBangDiemLSearch(idLop);
        if(dsbangdiem.size()>0)
        {
            DefaultTableModel dtm = (DefaultTableModel)tblBangDiem.getModel();
            dtm.setRowCount(0);//xóa các dòng cũ nếu có
            for(clsBangDiem bangdiem : dsbangdiem)
            {
             dtm.addRow(new Object[]{bangdiem.Msv, bangdiem.hoTen,bangdiem.idLop,bangdiem.idMon,bangdiem.tenMon, bangdiem.diem});
            }
        }
    }
    public void changeTable(JTable table, int column_index) {
        for(int i=0;i<=column_index;i++){
            table.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                    final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    float diem = Float.parseFloat(table.getValueAt(row, 5).toString());
                    if (diem>=(float)4) {
                        c.setBackground(Color.GREEN);
                    } else {
                        c.setBackground(Color.RED);
                    }
                    return c;
                }
            });
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangDiem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidLop = new javax.swing.JTextField();
        txtGVCN = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSuadiem = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 300));
        setSize(new java.awt.Dimension(600, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Msv", "Họ tên", "Lớp", "Mã môn", "Môn", "Điểm"
            }
        ));
        jScrollPane1.setViewportView(tblBangDiem);

        jLabel1.setText("Lớp");

        jLabel2.setText("GVCN");

        txtidLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidLopActionPerformed(evt);
            }
        });

        txtGVCN.setEditable(false);
        txtGVCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGVCNActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSuadiem.setText("Sửa điểm");
        btnSuadiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuadiemActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGVCN, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txtidLop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(btnSuadiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(14, 14, 14))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtidLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtGVCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(btnSuadiem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidLopActionPerformed

    private void txtGVCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGVCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGVCNActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String idLop = txtidLop.getText();
        tbBangDiem bangBangdiem = new tbBangDiem();
        tbLop bangLop = new tbLop();
        clsLop lop = bangLop.LayLop(idLop);
        txtGVCN.setText(lop.GVCN);
        Vector<clsBangDiem> dsbangdiem = bangBangdiem.LayDSBangDiemL(idLop);
            DefaultTableModel dtm = (DefaultTableModel)tblBangDiem.getModel();
            dtm.setRowCount(0);//xóa các dòng cũ nếu có
            for(clsBangDiem bangdiem : dsbangdiem)
            {
             dtm.addRow(new Object[]{bangdiem.Msv, bangdiem.hoTen,bangdiem.idLop,bangdiem.idMon,bangdiem.tenMon, bangdiem.diem});
            }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String idLop = this.idLop;
        tbBangDiem bangBangdiem = new tbBangDiem();
        tbLop bangLop = new tbLop();
        clsLop lop = bangLop.LayLop(idLop);
        txtGVCN.setText(lop.GVCN);
        txtidLop.setText(this.idLop);
        Vector<clsBangDiem> dsbangdiem = bangBangdiem.LayDSBangDiemLSearch(idLop);
        if(dsbangdiem.size()>0)
        {
            DefaultTableModel dtm = (DefaultTableModel)tblBangDiem.getModel();
            dtm.setRowCount(0);//xóa các dòng cũ nếu có
            for(clsBangDiem bangdiem : dsbangdiem)
            {
             dtm.addRow(new Object[]{bangdiem.Msv, bangdiem.hoTen,bangdiem.idLop,bangdiem.idMon,bangdiem.tenMon, bangdiem.diem});
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        csQLLop.HienthiDSLop();
        csQLLop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSuadiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuadiemActionPerformed
        // TODO add your handling code here:
        clsBangDiem ttBangDiem = new clsBangDiem();
        int i = tblBangDiem.getSelectedRow();
         if(i<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn sinh viên");
        else
        {
            ttBangDiem.Msv = (String)tblBangDiem.getModel().getValueAt(i,0);
            ttBangDiem.idMon = (String)tblBangDiem.getModel().getValueAt(i,3);
            ttBangDiem.idLop = (String)tblBangDiem.getModel().getValueAt(i,2);
            ttBangDiem.diem = (Float)tblBangDiem.getModel().getValueAt(i,5);
            if(ttBangDiem.diem>=4) ttBangDiem.tinhTrang = true;
            else ttBangDiem.tinhTrang = false;
            frmSuaDiem formSuaDiem = new frmSuaDiem();
            formSuaDiem.ttBangDiem = ttBangDiem;
            formSuaDiem.csBDLop = this;
            formSuaDiem.method =2;
            formSuaDiem.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSuadiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int i = tblBangDiem.getSelectedRow();
        if(i<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn bảng điểm");
        else
        {
            
            String Msv = (String)tblBangDiem.getModel().getValueAt(i,0);
            String idMon = (String)tblBangDiem.getModel().getValueAt(i,3);
            tbBangDiem bangBangDiem = new tbBangDiem();
            boolean kq = bangBangDiem.XoaBangDiem(Msv,idMon);
            if(kq==true)
            {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                HienthiDS("");
            }
            else
                JOptionPane.showMessageDialog(this, "Lỗi xóa sinh viên");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBangDiemL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBangDiemL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBangDiemL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBangDiemL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBangDiemL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSuadiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBangDiem;
    private javax.swing.JTextField txtGVCN;
    private javax.swing.JTextField txtidLop;
    // End of variables declaration//GEN-END:variables
}
