/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import CSDL.tbBangDiem;
import CSDL.tbSinhVien;
import Models.clsBangDiem;
import Models.clsLop;
import Models.clsMon;
import Models.clsSinhVien;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tantanmanh
 */
public class frmNhapDiem extends javax.swing.JFrame {
    clsMon ttMon;
    frmQuanlyMon csQLMon;
    /**
     * Creates new form frmNhapDiem
     */
    public frmNhapDiem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidMon = new javax.swing.JTextField();
        txttenMon = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbLop = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangDiem = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Mã môn");

        jLabel2.setText("Tên môn");

        txtidMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidMonActionPerformed(evt);
            }
        });

        txttenMon.setEditable(false);
        txttenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenMonActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");

        cbLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLopItemStateChanged(evt);
            }
        });
        cbLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLopActionPerformed(evt);
            }
        });

        tblBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Msv", "Họ tên", "Điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBangDiem.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tblBangDiemInputMethodTextChanged(evt);
            }
        });
        tblBangDiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblBangDiemKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblBangDiemKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tblBangDiem);

        btnThem.setText("Đồng ý");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnBack.setText("Đóng");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtidMon, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch)
                        .addGap(54, 54, 54))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnThem)
                .addGap(67, 67, 67)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnBack))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidMonActionPerformed

    private void txttenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenMonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        clsTienich.ComboBoxLophoc(cbLop,0);
        txtidMon.setText(ttMon.idMon);
        txttenMon.setText(ttMon.tenMon);
    }//GEN-LAST:event_formWindowOpened

    private void cbLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLopActionPerformed
        // TODO add your handling code here:
        if(cbLop.getSelectedIndex()>0)
        {
            clsLop lh = (clsLop) cbLop.getSelectedItem();
            tbSinhVien bangSinhVien = new tbSinhVien();
            Vector<clsSinhVien> dssinhvien = bangSinhVien.LayDSSinhvien(lh.idLop,5);
            if(dssinhvien.size()>0)
            {
                DefaultTableModel dtm = (DefaultTableModel)tblBangDiem.getModel();
                dtm.setRowCount(0);//xóa các dòng cũ nếu có
                for(clsSinhVien sinhvien : dssinhvien)
                {
                 dtm.addRow(new Object[]{sinhvien.Msv, sinhvien.hoTen});
                }
            }
        }
        else{
            DefaultTableModel dtm = (DefaultTableModel)tblBangDiem.getModel();
            dtm.setRowCount(0);//xóa các dòng cũ nếu có
        }
        
    }//GEN-LAST:event_cbLopActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try{
            int size = tblBangDiem.getRowCount();
            tbBangDiem bangBangDiem = new tbBangDiem();
            for(int i=0;i<size;i++){
                String Msv = (String)tblBangDiem.getModel().getValueAt(i,0);
                String idMon = this.ttMon.idMon;
                Float diem = (float)0;
                diem = (float)tblBangDiem.getModel().getValueAt(i,2);
                boolean tinhTrang = false;
                if (diem >(float)10){
                    JOptionPane.showMessageDialog(this, "Điểm vượt quá 10 sẽ được thay thế bằng 10");
                    diem = (float)10;
                }
                if(diem>=(float)4) tinhTrang = true;
                bangBangDiem.ThemBangDiem(Msv, idMon, diem, tinhTrang);
                csQLMon.HienthiDSMon();
                csQLMon.setVisible(true);
                this.dispose();
            }   
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra trong quá trình nhập bảng điểm");
        }
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        csQLMon.HienthiDSMon();
        csQLMon.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbLopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLopItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLopItemStateChanged

    private void tblBangDiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblBangDiemKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBangDiemKeyTyped

    private void tblBangDiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblBangDiemKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==109){
            JOptionPane.showMessageDialog(this, "Điểm không thể là số âm");
            tblBangDiem.getModel().setValueAt(0.0, tblBangDiem.getSelectedRow(), 2);
        }
        System.out.print(evt.getKeyCode());
    }//GEN-LAST:event_tblBangDiemKeyPressed

    private void tblBangDiemInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblBangDiemInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBangDiemInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhapDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhapDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhapDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhapDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhapDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBangDiem;
    private javax.swing.JTextField txtidMon;
    private javax.swing.JTextField txttenMon;
    // End of variables declaration//GEN-END:variables
}
